### ISSUE TITLE
English prescribing dataset with SNOMED

### ISSUE THREAD

**Issue by namor562** [PrAnaViz/PrAna#1]
Did you know that the NHSBSA also make available the English prescribing dataset with SNOMED via our Open Data Portal? This might be suitable and eliminate a few steps.
https://opendata.nhsbsa.net/dataset/english-prescribing-dataset-epd-with-snomed-code

**Comment by jkkishore85** [comment]
Hi @NadineMorrisroe, Thanks for the comment. I am aware of this, and presently working on to convert the new version (EPD) dataset for the total quantity calculations.

**Comment by namor562** [comment]
That's great to hear.
